### ISSUE TITLE
Need Admin Access

### ISSUE THREAD

**Issue by sub-mod** [thoth-station/tensorflow-trigger-job#1]
@harshad16  can you please add me as admin user.
We cannot do few admin actions on the repo if we don't have atleast one of the active developers in the Thoth Projects as owner of this repo.

**Comment by goern** [comment]
What do you want to do? What API permissions do you need?

**Comment by harshad16** [comment]
I have added the permission to the repository please have a look. 
Also, added the OWNER file in the repo. 😃

**Comment by sub-mod** [comment]
@harshad16 Thanks
And Thanks for all the good work done here.
